[build]
  command = "gatsby build"
  publish = "public"
  environment = { NODE_VERSION = "16", GATSBY_CPU_COUNT = "1" }

[build.environment]
  # Add environment variable to skip problematic operations
  LMDB_PRELOAD_THREADS = "0"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[edge_functions]]
  path = "/*"
  function = "language-redirect" 